# Menggunakan Docker Compose versi 2 atau lebih.
version: '3.7'

# Memiliki dua buah service: item-app dan item-db.
services:

  item-app:
    # Menggunakan image item-app dari Docker Hub
    image: yusufstawan/item-app:v1
    # Melakukan port mapping agar dapat diakses dari port 80 di host.
    ports:
      - 80:8080
    # item-app berjalan setelah item-db diluncurkan.
    depends_on:
      - item-db
    # menerapkan restart policy agar container selalu restart ketika terhenti
    restart: always

  item-db:
    # Menggunakan image mongo:3 dari Docker Hub.
    image: mongo:3
    # Memakai volume bernama app-db dengan target /data/db di container.
    volumes:
      - app-db:/data/db
    # menerapkan restart policy agar container selalu restart ketika terhenti
    restart: always

# Memiliki satu buah volume bernama app-db.
volumes:
  app-db:
